### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by iwanikhalid** [adiman-muhammad/Mathurat#2]
I will be doing this soonish insyaAllah

Refs
- https://special.worldofislam.info/index.php?page=Fortress_of_the_Muslim
- quran.com
- https://thequranblog.files.wordpress.com/2008/06/booklet-al-mathurat.pdf
- http://www.yusufmosque.com/wp-content/uploads/2009/06/mathurat-copy.pdf

**Comment by litium** [comment]
I have converted your .txt file to .sql file

**Comment by iwanikhalid** [comment]
Orait sorry tak sempat habiskan lagi. Nak cari the right translation challenging skek

**Comment by litium** [comment]
No worries. Takde rush nak kemana pon :P

**Comment by iwanikhalid** [comment]
Hehehe hey can you help me with PHP

```
$values = get_field('reviewer');
if($values)
{
	echo '<ul>';
	foreach($values as $value)
	{
		echo '<li>' . $value['display_name'] . '</li>';
	}
	echo '</ul>';
}
```

Macam mana I nak tukar <li> tu ke list biasa dengan comma je. 

Now it appears like

- Result 1
- Result 2
- Result 3

I just want Result 1, Result 2, Result 3

**Comment by litium** [comment]
`$values = get_field('reviewer');
if($values)
{
    foreach($values as $value)
    {
    	$display += $value['display_name'] . ', ';
    }
}`

Sorry lambat reply. Dunno if you already solve it but here goes

**Comment by litium** [comment]
oh why dia ilang semua indent??? 

:/

**Comment by iwanikhalid** [comment]
Haha I tulis kat notepad++ and copy paste here

Anyway, the code below didn't seem to work. Tak keluar apa2 

```
$values = get_field('reviewer'); 
if($values) { 
	foreach($values as $value) { 
		$display += $value['display_name'] . ', '; 
	} 
	echo substr($display, 0, -2); 
}
```

Ni var_dump if it helps

```
array(1) {
  [0]=&gt;
  array(11) {
    ["ID"]=&gt;
    string(2) "15"
    ["user_firstname"]=&gt;
    string(7) "Richard"
    ["user_lastname"]=&gt;
    string(4) "Hays"
    ["nickname"]=&gt;
    string(12) "Richard.Hays"
    ["user_nicename"]=&gt;
    string(12) "richard-hays"
    ["display_name"]=&gt;
    string(12) "Richard Hays"
    ["user_email"]=&gt;
    string(24) "Richard.Hays@utas.edu.au"
    ["user_url"]=&gt;
    string(0) ""
    ["user_registered"]=&gt;
    string(19) "2016-09-10 15:14:59"
    ["user_description"]=&gt;
    string(0) ""
    ["user_avatar"]=&gt;
    string(257) "<img alt="" src="http://0.gravatar.com/avatar/61cc08f3a0e37ce6720644a049991350?s=96&amp;d=mm&amp;r=g" srcset="http://0.gravatar.com/avatar/61cc08f3a0e37ce6720644a049991350?s=192&amp;d=mm&amp;r=g 2x" class="avatar avatar-96 photo" height="96" width="96">"
  }
}
```

**Comment by litium** [comment]
`values = get_field('reviewer');
if($values)
{
    foreach($values as $value) {
        $display .= $value['display_name'] . ‘, ’;
}
    echo substr($display, 0, -2);
}`

**Comment by litium** [comment]
i dah fix the code. tatau la kalau tak jadi gak. ekceli tadi silap += sepatutnya .=

**Comment by iwanikhalid** [comment]
Yayy dah work. But then results dia repeating plak eg:

```
Reviewer(s): Trudie Roberts, Trudie Roberts

Reviewer(s): Trudie Roberts, Trudie Roberts, Richard Hays, Trudie Roberts, Jim McKillop, Mafauzy Mohamed
```

Any idea why? Kalau tak, I'm just going to use ul li methinks

**Comment by litium** [comment]
repeating tu sebab your loop je tu. check the loop

**Comment by iwanikhalid** [comment]
Yayyyyyyyyyyyy I solved it!

```
$values = get_field('reviewer');										
$last = count($values) - 1;
foreach ($values as $i => $row)
{												
	//$isFirst = ($i == 0);								
	$isLast = ($i == $last);													
	if($isLast) :
		echo ''. $row['display_name'];
	else :
		echo $row['display_name'].', ';
	endif ;											
}
```

**Comment by litium** [comment]
@iwanikhalid u still alive?

**Comment by litium** [comment]
Closing issue. If anybody can continue where @iwanikhalid left off, is very much appreciated
