### ISSUE TITLE
Steps on how to contribute

### ISSUE THREAD

**Issue by PlashSpeed-Aiman** [adiman-muhammad/Mathurat#4]
Greetings, I'm building the an android app for al mathurat.

Can you show me how you obtained the texts? Do you write it manually or did you acquire from someplace else?

**Comment by adiman-dev** [comment]
Assalamualaikum

From various online sources and eyeball validation with printed text available such as the attached 

Any error/discrepancies are welcomed with a correction

![IMG_2314](https://github.com/adiman-dev/Mathurat/assets/1481171/70658149-8636-4bae-8977-faa79a2cf103)
